/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef loraprotocols_H_
#define loraprotocols_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

#define loraprotocols_MAXBW 5.E+5

extern uint32_t loraprotocols_BWTAB[10];

typedef uint32_t loraprotocols_IPNUM;

typedef uint32_t loraprotocols_UDPPORT;

struct loraprotocols_JDESTS;

typedef struct loraprotocols_JDESTS * loraprotocols_pJDESTS;


struct loraprotocols_JDESTS {
   loraprotocols_pJDESTS next;
   uint32_t jipnum;
   uint32_t judpport;
};

struct loraprotocols_FPAR;


struct loraprotocols_FPAR {
   float level;
   float minlev;
   float maxlev;
   float nf;
   float minnf;
   float maxnf;
   float snr;
   float drift;
   float snrmin;
   int32_t afchz;
   int32_t truedf;
   uint32_t txd;
   uint32_t frametime;
   uint32_t qual;
   uint32_t qualmin;
   uint32_t cr;
   uint32_t cfgsf;
   uint32_t synfilter;
   uint32_t label;
   uint32_t idfound;
   uint32_t illid;
   uint32_t fasecorrs;
   uint32_t fecbits;
   uint32_t firlen;
   char hascrc;
   char crc;
   char dcdlost;
   char invers;
   char ax25long;
   char udpcrcok;
   char axjoin;
   char dcd;
   char needsjunk;
   uint8_t phyhead[5];
   uint8_t phyheadlen;
   uint8_t loracrc[2];
   char has_loracrc;
};

extern uint32_t loraprotocols_hexformat;

extern uint32_t loraprotocols_bwnum;

extern int32_t loraprotocols_jsonfd;

extern int32_t loraprotocols_udpsock;

extern char loraprotocols_jpipename[1024];

extern char loraprotocols_hamview;

extern char loraprotocols_verb;

extern char loraprotocols_verb2;

extern char loraprotocols_newline;

extern char loraprotocols_quietcrc;

extern float loraprotocols_jmhz;

extern loraprotocols_pJDESTS loraprotocols_jdests0;

extern void loraprotocols_sendframe(char [], uint32_t, uint32_t,
                struct loraprotocols_FPAR, char [], uint32_t,
                char [], uint32_t, char [], uint32_t, uint32_t,
                 uint32_t, uint32_t, uint32_t, char);

extern void loraprotocols_senddcd(int32_t, char, char,
                float, float);


extern void loraprotocols_BEGIN(void);


#endif /* loraprotocols_H_ */
